services:
  session-safe-backend:
    image: session-safe-backend/session-safe-backend:v0
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - NODE_ENV=${NODE_ENV:-development}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    privileged: true
    command: >
      npm run dev;
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile.development
    image: onboarding-frontend-dev:latest
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}

volumes:
  pgdata:
