FROM node:22-alpine3.21

# Install Docker CLI
RUN apk update && apk add bash docker-cli && rm -rf /var/cache/apk/*

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

RUN docker build -f browser-session.Dockerfile -t browser-session .

EXPOSE 3000